// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebShop.Models
{
    [Table("Item")]
    public partial class Item
    {
        public int ItemId { get; set; }
        public int PurchaseOrderId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }

        [ForeignKey("ProductId")]
        [InverseProperty("Items")]
        public virtual Product Product { get; set; }
        [ForeignKey("PurchaseOrderId")]
        [InverseProperty("Items")]
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}