// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebShop.Models
{
    [Table("PurchaseOrder")]
    public partial class PurchaseOrder
    {
        public PurchaseOrder()
        {
            Items = new HashSet<Item>();
        }

        public int PurchaseOrderId { get; set; }
        [Required]
        [StringLength(450)]
        public string PersonId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateOfOrder { get; set; }

        [ForeignKey("PersonId")]
        [InverseProperty("PurchaseOrders")]
        public virtual Person Person { get; set; }
        [InverseProperty("PurchaseOrder")]
        public virtual ICollection<Item> Items { get; set; }
    }
}